runtime: java
env: flex

runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9


handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1

readiness_check:
  app_start_timeout_sec: 600