runtime: java
env: flex

runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9


handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1

readiness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  app_start_timeout_sec: 1500